name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Display path
      run: echo $PATH
    - name: Change the directory
      working-directory: ./KijijiScraping
      run: |
        npm install
        npm start


